import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  page: {
    flex: 1,
    padding: 10,
  },
  leftContainer: {
    marginRight: "auto",
  },
  rightContainer: {
    color: "#fff",
    marginLeft: "auto",
  },
  myMessage: {
    fontFamily: "Poppins_500Medium",
    fontSize: 15,
    backgroundColor: "#21FFB5",
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomLeftRadius: 12,
    borderTopLeftRadius: 12,
    borderBottomRightRadius: 0,
    borderTopRightRadius: 15,
    // borderRadius: 10,
    minWidth: 120,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 3,
  },
  myMessageWtImage: {
    fontFamily: "Poppins_500Medium",
    fontSize: 15,
    backgroundColor: "#21FFB5",
    color: "#fff",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomLeftRadius: 12,
    minWidth: 120,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 3,
  },
  yourMessage: {
    fontFamily: "Poppins_500Medium",
    backgroundColor: "#fff",
    color: "#656F99",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomRightRadius: 12,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    minWidth: 120,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 3,
  },
  yourMessageWtImage: {
    fontFamily: "Poppins_500Medium",
    backgroundColor: "#fff",
    color: "#656F99",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomRightRadius: 12,
    minWidth: 120,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 3,
  },
  wtMessage: {
    overflow: "hidden",
    backgroundColor: "#fff",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    marginBottom: 10,
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 5,
    width: 100 * 2.5,
  },
  noMessage: {
    backgroundColor: "#fff",
    borderRadius: 15,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.8,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 0,
    },
    elevation: 3,
  },
  square: {
    width: 100.0,
    height: 100.0,
    backgroundColor: "dodgerblue",
    borderRadius: 15,
  },
});

export default styles;
